# Generated by Django 3.0.10 on 2020-09-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumbmail',
            new_name='thumbnail',
        ),
    ]
